Tack 1
ayu-f/IntelligentPlacer pull request #1
Opened 2022-09-17 15:42 UTC by ayu-f

2022-10-12 23:15 UTC, AS2 requested changes

2022-10-12 23:15 UTC, AS2 commented on README.md
> +Дан набор фотографий предметов. Также даны фотографии многоугольника, нарисованного на белом листе с предметами из данного набора.
Не хочу показаться придирчивым, но может стоит здесь немного перефразировать: задача же состоит в том, чтоб разместить предметы в многоугольник, все которые изображены на ОДНОЙ фотографии, почему же ставится задача размещать объекты на множестве фотографий?

2022-10-12 23:15 UTC, AS2 commented on README.md
> +
Вопрос касательно многоугольника: допустимо ли, чтобы многоугольник был внутри закрашен? И, если да, то какое должно быть качество закраски маркером или ручкой? (не секрет же, что ручкой закрасить многоугольник А4 без пробелов тяжело, а закраска маркером может быть неоднотонной из-за свойств маркера). (Этот вопрос неявно отсылает к предыдущему комментарию).

Более того, не совсем понятно понятие "четко" в описании линий многоугольника: если представить, что Вы нарисовали черной ручкой подходящий под Ваши требования контур (замкнутый, без подтеков чернил, ровными отрезками по линейке), но сфотографировали на камеру так, что этот контур толщиной занимает будет буквально пару пикселей. Не получится ли так, что Ваш "четкий" (или, скорее, отличимый для человеческого глаза) многоугольник будет некорректно выделяться за счет указанных в плане операций? Может добавить требование к толщине линии, чтобы исключить даже такие гипотетические случаи плохого распознавания линий?

2022-10-12 23:15 UTC, AS2 commented on README.md
> +* Многоугольник расположен по одну сторону от всех предметов
По-своему опыту могу предположить, что условие "о взаимном расположении листа с многоугольником и предметов" будет считаться как упрощение задачи. Попробуйте подумать вот над чем: можно ли как то выделить маски предметов и многоугольника (или маску листа), а затем из полученного набора масок по какому-то критерию понять, какая маска принадлежит листу (или многоугольнику)? Может стоит воспользоваться информацией из входного изображения (например информацией о цвете предмета, который был выделен маской, или какой-то другой информацией)? Решив эту задачу, Вы сможете избавиться от этого требования и, как следствие, решать свою задачу как задачу без упрощений.

2022-10-12 23:15 UTC, AS2 commented on README.md
> +
Вы правильно подумали над тем, что стоит выделить некоторые ограничения на саму "сцену" входной фотографии (я говорю про блики и тени). Но я предлагаю Вам подумать еще вот над какими вопросами, ответы на которые, как мне кажется, помогут Вам дополнить Ваши требования новыми условиями или уточнить старые (или даже разработать более гибкий для входных данных код в будущем):
1) Можно ли использовать "неестественное" освещение (например, источник света, цвет которого совпадает с цветом фона? В таком же случае теряется цветовое отличие между белым и фоном и предметы становятся тяжело отличить).
2) Какие блики можно считать яркими? К примеру, блик на фотографии 'images/dataset/3.jpg' в пинцете достаточно сильный, чтобы точно его различить, однако блик есть и в крышечке 'images/dataset/1.jpg', который при этом не "портит" границу между объектом и фоном.

2022-10-12 23:15 UTC, AS2 commented on README.md
> +
Вот пару еще вопросов:
1) Чем принципиально отличается работа Вашего алгоритма с *.jpg изображениями от работы с, допустим, *.png изображениями?
2) Учитывает ли Ваш алгоритм все другие перспективные искажения, кроме как отклонений от перпендикуляра? Например, эффект "Рыбьего глаза", который присутствует во многих экшн-камерах? Если нет, то стоит указать это.
3) Есть ли какое то ограничение по расстоянию до поверхности? В конце концов, современные камеры имеют ограниченную разрешающую способность, из-за чего нарисованные ручкой многоугольники, изображенные на снимках с ооочень большого расстояния, могут быть плохо различимы.

2022-10-12 23:15 UTC, AS2 commented on README.md
> +
Ниже нет требований к поверхности, кроме как к освещенности самой поверхности.
Какого цвета может быть поверхность? Допустимо ли, чтоб она была одного цвета с листом бумаги или с цветом самих предметов? Может ли поверхность, побоюсь представить, светиться или отражать блики или прочие предметы из окружения? 
Думаю, ответы на эти вопросы сформируют более четкие критерии к поверхности, чем просто "различимость предметов на поверхности".

2022-10-12 23:15 UTC, AS2 commented on README.md
> +2. Найти границы с помощью детектора Canny (используя skimage.feature.canny)
Осмелюсь предположить, что использование детектора Canny может нечаянно привести к тому, что Вы получите большое число различных границ. Действительно ли Вам это нужно, если маски Вы, как ниже указываете, обнаруживаете при помощи "морфологических операций"?

2022-10-12 23:15 UTC, AS2 commented on README.md
> +4. Получить свойства предметов (их координаты границ). Многоугольником будет являться объект с наибольшей координатой Х(или с наибольшей интенсивностью полученных предметов(так как он белый)).
Здесь как раз Вы используете критерий, который позволяет избавиться от привязки к взаимному расположению предметов, что замечательно. Думаю, Вам стоит оставить только проверку на интенсивность предметов и подумать над тем, какие новые требования Вам стоит ввести, чтобы данный критерий мог работать безотказно.

2022-10-12 23:15 UTC, AS2 commented on README.md
> +5. Будем счиать, что один пиксель - один элемент матрицы
Это хорошо, что Вы предприняли попытку избавиться от перспективных искажений на фотографии. Такой метод действительно позволит избавиться от каких то элементарных искажений, по типу как съемка под углом (которые по Вашим требованиям как ни странно недопустимы). Однако, может ли данный поход избавиться от более сложных искажений, чем просто смещение и поворот (например, тот же самый "рыбий глаз")?
Более того, не совсем очевидно, как Вы будете связывать одну из масок, полученных в первом этапе работы алгоритма с нужной фотографией из набора (учитывая еще тот факт, что у многоугольника по идее нет фотографии из набора).
Думаю, Вам стоит или оставить и додумать этот этап работы [и тогда Вы сможете усложнить (в хорошем смысле) себе задачу, убрав требование к отсутствию наклонов или, может, значительно увеличив верхнюю границу допустимых отклонению], или убрать этот этап. В любом случае, Вам стоит указать в требованиях о различных искажениях входной фотографии, которые не моделируются как комбинация поворотов и смещений.

2022-10-12 23:15 UTC, AS2 commented on README.md
> +1. При неудачном размещении объекта поворачивать не на рандмоный угол, а на угол между предметом и границей многоугольника
У Вас в наборе присутствуют предметы, который в проекциях имеют не прямолинейные участки границ. Как Вы планируете рассчитывать угол между предметом (крышкой например) и прилегающей границей многоугольника?

2022-10-12 23:15 UTC, AS2 commented on README.md
> +8. Если удается разместить все предметы - возвращаем True, иначе False
Есть небольшой комментарий к алгоритму, над которым, как мне кажется, стоит подумать: у Вас нет ограничений на вход к разрешению изображения. В частности, оно может быть чрезвычайно большим: 10к х 10к. При этом маски будут, как следствие, тоже очень большого разрешения. Однако, смысл в этой большой точности может теряться, когда могут присутствовать какие то небольшие неточности (какая то небольшая тень, сглаживание масок и тд). Быть может стоит тогда сжимать все маски до какого-то меньшего размера, учитывая относительные размеры предметов относительно друг друга, чтобы уменьшить время работы алгоритма? (конечно, в сложности это остаются те же O(m*n) битовых операций и проверок на корректный результат этих самых битовых операций на каждый этап попытки размещения маски m х n, но что же мешает нам уменьшить это самое m).

2022-10-12 23:15 UTC, AS2 commented on README.md
> +3.
???
[зачем такой пункт?]

2022-10-12 23:15 UTC, AS2 commented on images/dataset/README.md
> +- 3.jpg - True
У Вас тут пинцет может плохо обнаружиться. 
(Это не ошибка, а просто комментарий)

2022-10-19 19:10 UTC, ayu-f commented on README.md
> +Дан набор фотографий предметов. Также даны фотографии многоугольника, нарисованного на белом листе с предметами из данного набора.
"фотографии многоугольника, нарисованного на белом листе с предметами из данного набора." - предполагают, что все изображены на ОДНОЙ фотографии. Первое предложение - речь о наборе данных

2022-10-19 19:15 UTC, ayu-f commented on README.md
> +
*>Вопрос касательно многоугольника: допустимо ли, чтобы многоугольник был внутри закрашен*
Все что не указано в постановке задачи явно - запрещено

*> не секрет же, что ручкой закрасить многоугольник А4 без пробелов тяжело*
Спорное утверждение 

*> Может добавить требование к толщине линии, чтобы исключить даже такие гипотетические случаи плохого распознавания линий?*
Хорошая идея, однако непонятно, как проверить толщину линии в программе в соответствии с постановкой.

2022-10-19 19:26 UTC, ayu-f commented on README.md
> +
*> Допустим ли цвет поверхности схожий с цветом предметов?*
Нет, указано в постановке в требовании к предметам "предметы хорошо различимы на ней"

В целом согласен, что стоит указать цвет поверхности

2022-10-19 19:27 UTC, ayu-f commented on README.md
> +2. Найти границы с помощью детектора Canny (используя skimage.feature.canny)
Такие детали, насколько я понимаю, определятся во время написания работы.

2022-10-19 19:32 UTC, ayu-f commented on README.md
> +1. При неудачном размещении объекта поворачивать не на рандмоный угол, а на угол между предметом и границей многоугольника
"Возможная оптимизация"
Как получать угол между непрямолинейными границами и границей многоугольника? 
Найти миниму из расстояний от границы фигуры и многоугольника, провести параллельную линию границе многоугольника через точку минимума

2022-10-19 19:35 UTC, ayu-f commented on README.md
> +8. Если удается разместить все предметы - возвращаем True, иначе False
Спасибо, добавлю требование по разрешению

2022-10-21 21:37 UTC, magliy reviewed
Дополнительных вопросов нет. Хорошая работа!

2022-10-22 14:50 UTC, AS2 commented on README.md
> +
> не секрет же, что ручкой закрасить многоугольник А4 без пробелов тяжело
> Спорное утверждение
Жду пруф где ручкой закрашен многоугольник без пробелов. Чтоб многоугольник по габаритам был примерно как многоугольник с фотографии 'images/4.jpg'))

2022-10-22 15:02 UTC, AS2 commented on README.md
> +
> Может добавить требование к толщине линии, чтобы исключить даже такие гипотетические случаи плохого распознавания линий?
> Хорошая идея, однако непонятно, как проверить толщину линии в программе в соответствии с постановкой.
Требования к входным данным подразумевают какие должны быть входные данные для корректной работы Вашего алгоритма и не более того. Т.е. Вы не обязаны проверять входные данные на выполнение каждого требования (ну это и логично, потому что некоторые требования, которые должны были бы выполняться для корректной работы, могут непросто проверяться).

2022-10-22 20:59 UTC, magliy commented
На мой взгляд самое главное, чтобы линия была различима. Толщина линии не имеет значение

С уважением,
Маглий Екатерина

Скачайте Outlook для iOS<https://aka.ms/o0ukef>
________________________________
От: Alex Sachuk ***@***.***>
Отправлено: Saturday, October 22, 2022 6:02:59 PM
Кому: ayu-f/IntelligentPlacer ***@***.***>
Копия: Маглий Екатерина Романовна ***@***.***>; Comment ***@***.***>
Тема: Re: [ayu-f/IntelligentPlacer] Task (PR #1)


@AS2 commented on this pull request.

________________________________

In README.md<https://github.com/ayu-f/IntelligentPlacer/pull/1#discussion_r1002502762>:

> +
+## Формат входных/выходных данных
+Программа на вход получает изображение формата .jpg, на котором расположен нарисованный многоугольник и предметы,
+которые необходимо проверить(по одну сторону от многоугольника)
+
+## Требования к многоугольнику
+* Многоугольник должен быть изображен на белом листе бумаги без лишних рисунков
+* Многоугольник должен быть нарисованн черным маркером или черной ручкой
+* Линии мноугольника должны быть четко прямыми, углы ярко выражены
+* Многоугольник должен быть замкнут
+* Многоугольник должен быть выпуклым
+* Многоугольник расположен по одну сторону от всех предметов
+* Не больше 5 вершин
+* Белый лист, на котором нарисован многоугольник, должен полностью помещаться на фотографии
+* Многоугольник должен быть строго справа относительно предметов
+


Может добавить требование к толщине линии, чтобы исключить даже такие гипотетические случаи плохого распознавания линий?
Хорошая идея, однако непонятно, как проверить толщину линии в программе в соответствии с постановкой.
Требования к входным данным подразумевают какие должны быть входные данные для корректной работы Вашего алгоритма и не более того. Т.е. Вы не обязаны проверять входные данные на выполнение каждого требования (ну это и логично, потому что некоторые требования, которые должны были бы выполняться для корректной работы, могут непросто проверяться).

—
Reply to this email directly, view it on GitHub<https://github.com/ayu-f/IntelligentPlacer/pull/1#discussion_r1002502762>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQHI4UHQJ6USE2Y35H6VALDWEP62HANCNFSM6AAAAAAQPBVNSI>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-10-23 14:27 UTC, merged